
# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Iman Azari
title: Senior Software Engineer
email: azari.dev@gmail.com
website: https://imanazari70.github.io/resume/

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username: imanazari70
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: iman-azari-4a881896
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Portfolio
  icon: fas fa-globe
  url: https://imanazari70.github.io/resume/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, I'm Iman Azari, a passionate Senior Software Engineer with over 8 years of hands-on experience in software development, infrastructure, DevOps, and data engineering. Holding a Master's degree in Computer Systems Architecture, I thrive on building scalable, efficient systems that drive innovation. My journey has taken me from rigorous testing and automation to architecting CI/CD pipelines, developing robust infrastructures with Python, and crafting backend services using Django. I'm particularly excited about emerging technologies like LLMs and agent-based systems, where I've contributed to high-impact products processing real-time data streams with Flink.

  I am most skilled in: <mark>Python</mark> and <mark>Django</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: High-Throughput Stream Processing System
        link: github.com/imanazari70
        # link_text: Project Website
        additional_links:
          - title:  imanazari70/flink-stream-processor
            icon: fab fa-github
            url: github.com/imanazari70/flink-stream-processor
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A scalable data pipeline leveraging Apache Flink for real-time processing of high-velocity streams, ensuring low-latency insights for large-scale applications.
        description: | # this will include new lines to allow paragraphs
          Designed and implemented a robust stream processing infrastructure to handle massive data inflows, integrating Flink for fault-tolerant, stateful computations. This project optimized performance for a major product, reducing processing times by 40% while maintaining data integrity across distributed environments.

      - layout: top-middle
        title: LLM-Powered Agent Framework
        link: github.com/imanazari70
        # link_text: Project Website
        additional_links:
          - title:  imanazari70/llm-agent-builder
            icon: fab fa-github
            url: github.com/imanazari70/llm-agent-builder
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          An innovative framework for constructing intelligent agents using Large Language Models, enabling autonomous task orchestration and decision-making.
        description: | # this will include new lines to allow paragraphs
          Built a modular system that harnesses LLMs to create adaptive agents for complex workflows. Incorporated Python best practices, Docker containerization, and unit testing to ensure reliability. This initiative has been pivotal in prototyping AI-driven products, showcasing my expertise in cutting-edge AI integrations.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Nahane Adineh Mahsan
        link: nahaneadineh.com
        # link_text: nahaneadineh.com
        sub_title: Backend Developer
        caption: October 2023 - Present
        quote: >
          Driving backend innovation with scalable Django applications and exploring AI frontiers through LLM integrations.
        description: | # this will include new lines to allow paragraphs
          Leading the development and maintenance of core Django-based products, ensuring high availability and performance. Gained hands-on experience in data engineering with Apache Flink for high-throughput stream processing, and pioneered LLM applications by building agent-based systems to automate intelligent workflows.

      - layout: left
        title: Nahane Adineh Mahsan
        link: nahaneadineh.com
        # link_text: nahaneadineh.com
        sub_title: Infrastructure Engineer
        caption: October 2020 - September 2023
        quote: >
          Architecting resilient infrastructures that power enterprise-scale testing and deployment ecosystems.
        description: | # this will include new lines to allow paragraphs
          Developed Python-driven infrastructure solutions, including a comprehensive system for requirement ingestion, automated test execution, and result comparison for large-scale products. Emphasized clean code principles, unit testing, and containerization with Docker to enhance scalability and maintainability.

      - layout: left
        title: Nahane Adineh Mahsan
        link: nahaneadineh.com
        # link_text: nahaneadineh.com
        sub_title: DevOps Engineer
        caption: October 2018 - September 2020
        quote: >
          Streamlining development lifecycles through automated CI/CD pipelines, fostering faster and more reliable releases.
        description: | # this will include new lines to allow paragraphs
          Engineered and maintained CI/CD pipelines using Jenkins, optimizing build, test, and deployment processes. Collaborated cross-functionally to integrate tools like Docker Compose and Kubernetes, reducing deployment times and minimizing errors in production environments.

      - layout: left
        title: Nahane Adineh Mahsan
        link: nahaneadineh.com
        # link_text: nahaneadineh.com
        sub_title: QA Tester
        caption: October 2016 - September 2018
        quote: >
          Ensuring product excellence through rigorous testing and automation, laying the foundation for quality-driven engineering.
        description: | # this will include new lines to allow paragraphs
          Conducted comprehensive product testing and authored automated test suites using Selenium and Appium. Identified critical defects early in the cycle, contributing to robust software releases and a culture of continuous improvement.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Khajeh Nasir Toosi University of Technology
        caption: 2015 - 2017
        sub_title: MSc in Computer Systems Architecture
        quote: >
          A leading Iranian university renowned for its rigorous engineering programs and focus on advanced computational systems.
        description: | # this will include new lines to allow paragraphs
          Deepened expertise in system design, parallel computing, and architectural principles, preparing me for complex infrastructure challenges. Engaged in research projects emphasizing performance optimization and scalable architectures.

      - layout: left
        title: University of Tehran
        caption: 2009 - 2014
        sub_title: BSc in Computer Engineering
        quote: >
          Iran's premier university, celebrated for its excellence in science and engineering, fostering innovation and critical thinking.
        description: | # this will include new lines to allow paragraphs
          Built a strong foundation in computer science fundamentals, software engineering, and problem-solving. Participated in collaborative projects that honed my skills in teamwork and applying theoretical knowledge to practical applications.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Beyond coding and system architecture, I enjoy exploring new technologies, contributing to open-source communities, and staying active through hiking and reading sci-fi novels. I'm committed to clean code practices, writing unit tests, and mentoring juniors to build high-performing teams.

      Look at this cool image  
      ![Profile](/modern-resume-theme/images/profile.jpg "Profile")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
